"""Context generation — `soma context <project>`, THE product.

Renders the strict summary format defined in CLAUDE.md from git history
plus file mtimes. Blockers are heuristic and always phrased as "detected",
never asserted. Hard token ceiling: files truncate first, then commits;
branch, blockers, confidence and focus are never dropped.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from pathlib import Path

from soma.config import load_config
from soma.notes import MAX_NOTES, load_notes
from soma.sanitize import redact
from soma.status import CommitInfo, ProjectStatus, get_status, humanize_delta
from soma.context_git import (
    _fetch_commit_stats,
    _files_in_motion,
    _recent_files_by_mtime,
    _walk_files,
)
from soma.context_heuristics import (
    _confidence,
    _detect_blockers,
    _extract_readme_paragraph,
    _is_todo_stale,
    _project_description,
    _readme_preamble,
    _suggested_focus,
    _todo_blockers,
    _top_dir,
)

TOKEN_CEILING = 600
MAX_FILES = 8
MAX_COMMITS = 5
STALE_DAYS = 7
EVENTS_DIR = Path.home() / ".soma" / "events"


class UnsafeTargetError(RuntimeError):
    """CLAUDE.md exists and wasn't generated by SOMA — refuse to overwrite."""


def write_context_file(root: Path, text: str, target_path: Path | None = None) -> Path:
    """Write the summary to <root>/CLAUDE.md or target_path — only ever over SOMA's own output if it is named CLAUDE.md."""
    target = target_path or (root / "CLAUDE.md")
    if target.exists() and target.name == "CLAUDE.md":
        try:
            lines = target.read_text(encoding="utf-8", errors="ignore").splitlines()
        except OSError:
            lines = []
        first = lines[0] if lines else ""
        if first and "by SOMA)" not in first:
            raise UnsafeTargetError(
                f"{target} exists and was not generated by SOMA — refusing to overwrite"
            )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8", newline="\n")
    return target


def estimate_tokens(text: str) -> int:
    """Cheap token estimate (~4 chars/token for English + markdown)."""
    return max(1, len(text) // 4)


def generate_context_dict(
    name: str,
    root: Path,
    now: datetime | None = None,
    since: datetime | None = None,
) -> dict:
    """Return structured context data as a plain dict (for --format json)."""
    cfg = load_config()
    now = now or datetime.now(timezone.utc)
    status = get_status(name, root, since=since)
    description = _project_description(root)
    notes = load_notes(name)
    commit_stats = _fetch_commit_stats(root, cfg["max_commits"])
    files = _files_in_motion(root, status.files_changed_7d)
    if not files:
        files = _recent_files_by_mtime(root, now, dormant_days=cfg["dormant_days"])
    blockers = _detect_blockers(status, root, files, now)
    focus = _suggested_focus(status, files, now, dormant_days=cfg["dormant_days"])
    confidence = _confidence(status)
    return {
        "project": name,
        "generated": now.isoformat(),
        "branch": status.branch,
        "last_active": status.last_active.isoformat() if status.last_active else None,
        "commits_7d": status.commits_7d,
        "files_changed": len(status.files_changed_7d),
        "confidence": confidence,
        # Security gate: the JSON path must redact too. Commit messages are
        # already clean (redacted in status.py); description / focus / notes
        # are redacted here so no render path leaks credentials.
        "description": redact(description),
        "recent_commits": [
            {"message": c.message, "when": c.when.isoformat()}
            for c in status.recent_commits[: cfg["max_commits"]]
        ],
        "files_in_motion": [
            {"path": rel, "modified": when.isoformat()}
            for rel, when in files[: cfg["max_files"]]
        ],
        "blockers": [redact(b) for b in blockers],
        "focus": redact(focus),
        "notes": [{"text": redact(n.text), "when": n.when} for n in notes[:MAX_NOTES]],
    }


def generate_context(
    name: str,
    root: Path,
    now: datetime | None = None,
    max_tokens: int | None = None,
    since: datetime | None = None,
) -> str:
    """Build the compact context summary for one project. Never raises on
    missing data — empty repos and non-git dirs produce valid output."""
    cfg = load_config()
    effective_ceiling = max_tokens if max_tokens is not None else cfg["token_ceiling"]
    cfg_max_files = cfg["max_files"]
    cfg_max_commits = cfg["max_commits"]
    cfg_dormant_days = cfg["dormant_days"]

    now = now or datetime.now(timezone.utc)
    status = get_status(name, root, since=since)
    description = _project_description(root)
    notes = load_notes(name)
    commit_stats = _fetch_commit_stats(root, cfg_max_commits)
    files = _files_in_motion(root, status.files_changed_7d)
    if not files:
        files = _recent_files_by_mtime(root, now, dormant_days=cfg_dormant_days)
    blockers = _detect_blockers(status, root, files, now)
    focus = _suggested_focus(status, files, now, dormant_days=cfg_dormant_days)
    confidence = _confidence(status)

    n_files, n_commits = cfg_max_files, cfg_max_commits
    text = _render(name, description, notes, status, commit_stats, files, blockers, focus, confidence, now, n_files, n_commits, since=since)
    while estimate_tokens(text) > effective_ceiling and n_files > 0:
        n_files -= 1
        text = _render(name, description, notes, status, commit_stats, files, blockers, focus, confidence, now, n_files, n_commits, since=since)
    while estimate_tokens(text) > effective_ceiling and n_commits > 1:
        n_commits -= 1
        text = _render(name, description, notes, status, commit_stats, files, blockers, focus, confidence, now, n_files, n_commits, since=since)
    return redact(text)


def _fmt_commit(c: CommitInfo, stats: tuple[int, int] | None, now: datetime) -> str:
    time_str = humanize_delta(c.when, now)
    if stats and (stats[0] or stats[1]):
        return f"- {c.message} (+{stats[0]}/-{stats[1]}) ({time_str})"
    return f"- {c.message} ({time_str})"


def _render(
    name: str,
    description: str,
    notes: list,
    status: ProjectStatus,
    commit_stats: list[tuple[int, int]],
    files: list[tuple[str, datetime]],
    blockers: list[str],
    focus: str,
    confidence: str,
    now: datetime,
    n_files: int,
    n_commits: int,
    since: datetime | None = None,
) -> str:
    import re  # noqa: PLC0415
    commit_lines = [
        _fmt_commit(c, commit_stats[i] if i < len(commit_stats) else None, now)
        for i, c in enumerate(status.recent_commits[:n_commits])
    ] or ["- (no commits found)"]
    file_lines = [
        f"- {rel} ({humanize_delta(when, now)})" for rel, when in files[:n_files]
    ] or ["- (no recent file changes)"]
    blocker_lines = [f"- {b}" for b in blockers] or ["- None detected"]
    # Mtime-only edits inside the window must not read as "0 files changed".
    edited_in_window = sum(
        1 for _, when in files if now - when <= timedelta(days=STALE_DAYS)
    )
    window_label = f"since {since:%Y-%m-%d}" if since else "7d"
    if status.commits_7d == 0 and not status.files_changed_7d and edited_in_window:
        plural = "file" if edited_in_window == 1 else "files"
        activity = (
            f"**Activity ({window_label}):** 0 commits, {edited_in_window} {plural} edited (uncommitted)"
        )
    else:
        activity = (
            f"**Activity ({window_label}):** {status.commits_7d} commits, "
            f"{len(status.files_changed_7d)} files changed"
        )
    parts = [
        f"# {name} — Context Summary (generated {now:%Y-%m-%d} by SOMA)",
        "",
        f"**Branch:** {status.branch} | **Last active:** {humanize_delta(status.last_active, now)}",
        activity,
        f"**Confidence:** {confidence}",
    ]
    if description:
        parts += ["", f"**What this is:** {description}"]
    if notes:
        parts += ["", "## Notes"]
        for n in notes[:MAX_NOTES]:
            when = humanize_delta(datetime.fromisoformat(n.when), now)
            parts.append(f"- {n.text} ({when})")
    parts += [
        "",
        "## Recent work",
        *commit_lines,
        "",
        "## Files in motion",
        *file_lines,
        "",
        "## Possible blockers",
        *blocker_lines,
        "",
        "## Suggested focus",
        focus,
        "",
    ]
    return "\n".join(parts)