"""Context generation — `soma context <project>`, THE product.

Renders the strict summary format defined in CLAUDE.md from git history
plus file mtimes. Blockers are heuristic and always phrased as "detected",
never asserted. Hard token ceiling: files truncate first, then commits;
branch, blockers, confidence and focus are never dropped.
"""
from __future__ import annotations

import os
import re
import time
from collections import Counter
from datetime import datetime, timedelta, timezone
from pathlib import Path

from soma.filters import is_watched, should_ignore
from soma.notes import MAX_NOTES, load_notes
from soma.sanitize import redact
from soma.status import CommitInfo, ProjectStatus, get_status, humanize_delta

TOKEN_CEILING = 600
MAX_FILES = 8
MAX_COMMITS = 5
MAX_BLOCKERS = 3
STALE_DAYS = 7
DORMANT_DAYS = 30  # threshold for "dormant" suggested focus
FIX_STORM_WINDOW = timedelta(hours=24)
FIX_STORM_THRESHOLD = 3  # flag when strictly more fix commits than this
TODO_READ_CAP = 200_000  # bytes per file scanned for TODO/FIXME
README_READ_CAP = 4_000   # bytes — first meaningful paragraph only
README_DESC_MAX = 350     # chars of description to surface
FILE_WALK_BUDGET_S = 0.3

# v1 has no event writer; checked for forward compatibility, git is the source.
EVENTS_DIR = Path.home() / ".soma" / "events"


class UnsafeTargetError(RuntimeError):
    """CLAUDE.md exists and wasn't generated by SOMA — refuse to overwrite."""


def write_context_file(root: Path, text: str) -> Path:
    """Write the summary to <root>/CLAUDE.md — only ever over SOMA's own output.

    A CLAUDE.md whose first line lacks the "by SOMA)" marker is someone's
    hand-written agent contract; overwriting it would destroy real work.
    """
    target = root / "CLAUDE.md"
    if target.exists():
        try:
            lines = target.read_text(encoding="utf-8", errors="ignore").splitlines()
        except OSError:
            lines = []
        first = lines[0] if lines else ""
        if first and "by SOMA)" not in first:
            raise UnsafeTargetError(
                f"{target} exists and was not generated by SOMA — refusing to overwrite"
            )
    target.write_text(text, encoding="utf-8", newline="\n")
    return target


def estimate_tokens(text: str) -> int:
    """Cheap token estimate (~4 chars/token for English + markdown)."""
    return max(1, len(text) // 4)


def generate_context(
    name: str,
    root: Path,
    now: datetime | None = None,
    max_tokens: int = TOKEN_CEILING,
) -> str:
    """Build the compact context summary for one project. Never raises on
    missing data — empty repos and non-git dirs produce valid output."""
    now = now or datetime.now(timezone.utc)
    status = get_status(name, root)
    description = _project_description(root)
    notes = load_notes(name)
    commit_stats = _fetch_commit_stats(root, MAX_COMMITS)
    files = _files_in_motion(root, status.files_changed_7d)
    if not files:
        files = _recent_files_by_mtime(root, now)
    blockers = _detect_blockers(status, root, files, now)
    focus = _suggested_focus(status, files, now)
    confidence = _confidence(status)

    n_files, n_commits = MAX_FILES, MAX_COMMITS
    text = _render(name, description, notes, status, commit_stats, files, blockers, focus, confidence, now, n_files, n_commits)
    while estimate_tokens(text) > max_tokens and n_files > 0:
        n_files -= 1
        text = _render(name, description, notes, status, commit_stats, files, blockers, focus, confidence, now, n_files, n_commits)
    while estimate_tokens(text) > max_tokens and n_commits > 1:
        n_commits -= 1
        text = _render(name, description, notes, status, commit_stats, files, blockers, focus, confidence, now, n_files, n_commits)
    return redact(text)


def _fetch_commit_stats(root: Path, n: int) -> list[tuple[int, int]]:
    """(insertions, deletions) for the last n commits. Empty list on any error."""
    try:
        from git import Repo  # noqa: PLC0415
        from git.exc import GitCommandError, InvalidGitRepositoryError  # noqa: PLC0415

        repo = Repo(root)
        out = repo.git.log(f"--max-count={n}", "--pretty=format:COMMIT", "--shortstat")
    except Exception:
        return []
    stats: list[tuple[int, int]] = []
    ins, dels = 0, 0
    in_commit = False
    for line in out.splitlines():
        stripped = line.strip()
        if stripped == "COMMIT":
            if in_commit:
                stats.append((ins, dels))
            ins, dels, in_commit = 0, 0, True
        elif in_commit and stripped:
            m_ins = re.search(r"(\d+) insertion", stripped)
            m_del = re.search(r"(\d+) deletion", stripped)
            ins += int(m_ins.group(1)) if m_ins else 0
            dels += int(m_del.group(1)) if m_del else 0
    if in_commit:
        stats.append((ins, dels))
    return stats


def _fmt_commit(c: CommitInfo, stats: tuple[int, int] | None, now: datetime) -> str:
    time_str = humanize_delta(c.when, now)
    if stats and (stats[0] or stats[1]):
        return f"- {c.message} (+{stats[0]}/-{stats[1]}) ({time_str})"
    return f"- {c.message} ({time_str})"


def _render(
    name: str,
    description: str,
    notes: list,
    status: ProjectStatus,
    commit_stats: list[tuple[int, int]],
    files: list[tuple[str, datetime]],
    blockers: list[str],
    focus: str,
    confidence: str,
    now: datetime,
    n_files: int,
    n_commits: int,
) -> str:
    commit_lines = [
        _fmt_commit(c, commit_stats[i] if i < len(commit_stats) else None, now)
        for i, c in enumerate(status.recent_commits[:n_commits])
    ] or ["- (no commits found)"]
    file_lines = [
        f"- {rel} ({humanize_delta(when, now)})" for rel, when in files[:n_files]
    ] or ["- (no recent file changes)"]
    blocker_lines = [f"- {b}" for b in blockers] or ["- None detected"]
    # Mtime-only edits inside the window must not read as "0 files changed".
    edited_in_window = sum(
        1 for _, when in files if now - when <= timedelta(days=STALE_DAYS)
    )
    if status.commits_7d == 0 and not status.files_changed_7d and edited_in_window:
        plural = "file" if edited_in_window == 1 else "files"
        activity = (
            f"**Activity (7d):** 0 commits, {edited_in_window} {plural} edited (uncommitted)"
        )
    else:
        activity = (
            f"**Activity (7d):** {status.commits_7d} commits, "
            f"{len(status.files_changed_7d)} files changed"
        )
    parts = [
        f"# {name} — Context Summary (generated {now:%Y-%m-%d} by SOMA)",
        "",
        f"**Branch:** {status.branch} | **Last active:** {humanize_delta(status.last_active, now)}",
        activity,
        f"**Confidence:** {confidence}",
    ]
    if description:
        parts += ["", f"**What this is:** {description}"]
    if notes:
        parts += ["", "## Notes"]
        for n in notes[:MAX_NOTES]:
            when = humanize_delta(datetime.fromisoformat(n.when), now)
            parts.append(f"- {n.text} ({when})")
    parts += [
        "",
        "## Recent work",
        *commit_lines,
        "",
        "## Files in motion",
        *file_lines,
        "",
        "## Possible blockers",
        *blocker_lines,
        "",
        "## Suggested focus",
        focus,
        "",
    ]
    return "\n".join(parts)


def _files_in_motion(root: Path, candidates: list[str]) -> list[tuple[str, datetime]]:
    """Attach mtimes to git-changed paths, newest first (deleted files drop out)."""
    out: list[tuple[str, datetime]] = []
    for rel in candidates:
        try:
            ts = (root / rel).stat().st_mtime
        except OSError:
            continue
        out.append((rel, datetime.fromtimestamp(ts, tz=timezone.utc)))
    out.sort(key=lambda item: item[1], reverse=True)
    return out[:MAX_FILES]


def _recent_files_by_mtime(
    root: Path, now: datetime | None = None
) -> list[tuple[str, datetime]]:
    """Fallback for non-git/quiet repos: newest watched files by mtime.

    Files older than DORMANT_DAYS are omitted — showing 86d-old files as
    "in motion" is misleading for dormant repos.
    """
    now = now or datetime.now(timezone.utc)
    cutoff = (now - timedelta(days=DORMANT_DAYS)).timestamp()
    deadline = time.monotonic() + FILE_WALK_BUDGET_S
    found: list[tuple[str, float]] = []
    _walk_files(str(root), root, deadline, found)
    found.sort(key=lambda item: item[1], reverse=True)
    return [
        (rel, datetime.fromtimestamp(ts, tz=timezone.utc))
        for rel, ts in found[:MAX_FILES]
        if ts >= cutoff
    ]


def _walk_files(
    directory: str, root: Path, deadline: float, found: list[tuple[str, float]]
) -> None:
    if time.monotonic() > deadline:
        return
    try:
        with os.scandir(directory) as it:
            for entry in it:
                name = entry.name
                if name.startswith("."):
                    continue
                try:
                    if entry.is_dir(follow_symlinks=False):
                        if not should_ignore(name):
                            _walk_files(entry.path, root, deadline, found)
                    elif is_watched(name) and not should_ignore(name):
                        ts = entry.stat(follow_symlinks=False).st_mtime
                        rel = Path(entry.path).relative_to(root).as_posix()
                        found.append((rel, ts))
                except (OSError, ValueError):
                    continue
    except OSError:
        pass


def _detect_blockers(
    status: ProjectStatus,
    root: Path,
    files: list[tuple[str, datetime]],
    now: datetime,
) -> list[str]:
    blockers: list[str] = []
    last_commit = status.recent_commits[0].when if status.recent_commits else None
    if last_commit is not None and now - last_commit > timedelta(days=STALE_DAYS):
        if status.last_active is not None and status.last_active > last_commit:
            blockers.append(
                "Possible blocker detected: stale branch — no commit since "
                f"{humanize_delta(last_commit, now)}; file edits "
                f"{humanize_delta(status.last_active, now)} postdate last commit"
            )
    fixes = [
        c
        for c in status.recent_commits
        if "fix" in c.message.lower() and now - c.when <= FIX_STORM_WINDOW
    ]
    if len(fixes) > FIX_STORM_THRESHOLD:
        blockers.append(
            f"Possible blocker detected: fix storm — {len(fixes)} fix commits in the last 24h"
        )
    blockers.extend(_todo_blockers(root, files))
    return blockers[:MAX_BLOCKERS]


def _todo_blockers(root: Path, files: list[tuple[str, datetime]]) -> list[str]:
    # Only the path is reported, never file content — content could hold secrets.
    out: list[str] = []
    for rel, _ in files[:MAX_FILES]:
        try:
            with open(root / rel, encoding="utf-8", errors="ignore") as f:
                text = f.read(TODO_READ_CAP)
        except OSError:
            continue
        if re.search(r"(?:^|[\s#/\*])(TODO|FIXME)\s*[:\(]", text, re.MULTILINE):
            out.append(
                f"Possible blocker detected: TODO/FIXME in recently modified {rel}"
            )
        if len(out) >= 2:
            break
    return out


def _confidence(status: ProjectStatus) -> str:
    if status.commits_7d > 0:
        return "high"
    if status.recent_commits:
        return "medium"
    return "low"


def _project_description(root: Path) -> str:
    """Extract a short functional description from README (first real paragraph)
    or pyproject.toml. Strips markdown noise; prefers sentences over taglines."""
    for readme in ("README.md", "README.rst", "README.txt", "readme.md"):
        path = root / readme
        if path.exists():
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")[:README_READ_CAP]
            except OSError:
                continue
            desc = _extract_readme_paragraph(text)
            if desc:
                return desc
    pyproject = root / "pyproject.toml"
    if pyproject.exists():
        try:
            import tomllib  # type: ignore[import]
        except ImportError:
            try:
                import tomli as tomllib  # type: ignore[import,no-redef]
            except ImportError:
                return ""
        try:
            with open(pyproject, "rb") as f:
                data = tomllib.load(f)
            desc = data.get("project", {}).get("description", "")
            if desc:
                return str(desc)[:README_DESC_MAX]
        except Exception:
            pass
    return ""


def _extract_readme_paragraph(text: str) -> str:
    """Return the first real prose paragraph from README text.

    Prefers paragraphs that read as functional descriptions (contain a verb-like
    word: is/does/builds/provides/helps/lets/runs/generates/scans/manages).
    Falls back to any paragraph with a complete sentence (contains a period/colon).
    Finally falls back to first non-trivial line.
    """
    SKIP_PREFIXES = ("#", "!", "<", "`", "[", "|", "---", "===", "~~~")
    VERB_WORDS = re.compile(
        r"\b(is|are|does|builds|provides|helps|lets|runs|generates|scans|manages"
        r"|creates|tracks|allows|enables|installs|parses|reads|writes|converts"
        r"|a proof|a cli|a tool|a library|a framework)\b",
        re.I,
    )

    def clean_line(line: str) -> str:
        line = line.strip()
        if line.startswith(">"):
            line = line.lstrip("> ").strip()
        # Strip markdown bold/italic (* and _)
        line = re.sub(r"[*_]{1,3}(.+?)[*_]{1,3}", r"\1", line)
        return line

    paragraphs: list[str] = []
    current: list[str] = []
    for raw in text.splitlines():
        raw_stripped = raw.strip()
        if not raw_stripped:
            if current:
                paragraphs.append(" ".join(current))
                current = []
            continue
        if any(raw_stripped.startswith(p) for p in SKIP_PREFIXES):
            if current:
                paragraphs.append(" ".join(current))
                current = []
            continue
        cleaned = clean_line(raw_stripped)
        if len(cleaned) > 15:
            current.append(cleaned)
    if current:
        paragraphs.append(" ".join(current))

    def strip_md(s: str) -> str:
        s = re.sub(r"[*_]{1,3}(.+?)[*_]{1,3}", r"\1", s)
        s = re.sub(r"`(.+?)`", r"\1", s)
        return s

    # Prefer paragraphs with functional verb words
    for para in paragraphs:
        if VERB_WORDS.search(para) and len(para) > 30:
            return strip_md(para)[:README_DESC_MAX]
    # Fall back: any paragraph with a sentence-ending marker
    for para in paragraphs:
        if ("." in para or ":" in para) and len(para) > 30:
            return strip_md(para)[:README_DESC_MAX]
    # Last resort: first non-trivial paragraph
    for para in paragraphs:
        if len(para) > 20:
            return strip_md(para)[:README_DESC_MAX]
    return ""


def _suggested_focus(
    status: ProjectStatus,
    files: list[tuple[str, datetime]],
    now: datetime,
) -> str:
    last_commit = status.recent_commits[0].when if status.recent_commits else None
    dormant = last_commit is not None and (now - last_commit) > timedelta(days=DORMANT_DAYS)
    if status.recent_commits:
        message = status.recent_commits[0].message
        if dormant:
            return (
                f'Dormant {int((now - last_commit).days)}d — '  # type: ignore[arg-type]
                f'review goals then resume from: "{message}"'
            )
        top = _top_dir(files)
        if top:
            return f'Continue recent work in `{top}/` — last commit: "{message}"'
        return f'Continue from last commit: "{message}"'
    if files:
        return f"Resume editing {files[0][0]} (most recently touched file)"
    return "No recent activity detected — review project goals before starting"


_SKIP_TOP_DIRS = frozenset(
    {"tests", "test", "docs", "doc", "__pycache__", ".github", "node_modules", "dist", "build"}
)


def _top_dir(files: list[tuple[str, datetime]]) -> str | None:
    dirs = [
        rel.split("/")[0]
        for rel, _ in files
        if "/" in rel and rel.split("/")[0] not in _SKIP_TOP_DIRS
    ]
    if not dirs:
        return None
    return Counter(dirs).most_common(1)[0][0]
