"""Activity history: timestamped commit events grouped per day per project.

Data source is git log only — quiet and non-git projects simply contribute
no events. Markdown export targets Obsidian notes and standups.
"""
from __future__ import annotations

from datetime import date, datetime, timezone
from pathlib import Path

from git import InvalidGitRepositoryError, NoSuchPathError, Repo
from git.exc import GitCommandError
from pydantic import BaseModel


class HistoryEvent(BaseModel):
    when: datetime
    project: str
    message: str


def collect_history(
    registry: dict[str, dict],
    days: int = 7,
    project: str | None = None,
) -> dict[date, list[HistoryEvent]]:
    """Commit events in the window, grouped by day, newest day first.

    Within a day, events are newest first. Projects without git history
    are skipped quietly.
    """
    events: list[HistoryEvent] = []
    for name, entry in registry.items():
        if project is not None and name != project:
            continue
        events.extend(_project_events(name, Path(entry["root"]), days))
    events.sort(key=lambda e: e.when, reverse=True)
    grouped: dict[date, list[HistoryEvent]] = {}
    for event in events:
        grouped.setdefault(event.when.date(), []).append(event)
    return grouped


def render_markdown(days: dict[date, list[HistoryEvent]]) -> str:
    """Obsidian/standup-friendly markdown: one ## header per day."""
    lines = ["# Activity log (generated by SOMA)", ""]
    if not days:
        lines.append("No activity in this window.")
    for day in sorted(days, reverse=True):
        lines.append(f"## {day.isoformat()}")
        for event in days[day]:
            lines.append(
                f"- {event.when:%H:%M} — **{event.project}**: {event.message}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _project_events(name: str, root: Path, days: int) -> list[HistoryEvent]:
    try:
        repo = Repo(root)
        out = repo.git.log(f"--since={days}.days.ago", "--pretty=format:%ct%x09%s")
    except (InvalidGitRepositoryError, NoSuchPathError, GitCommandError):
        return []
    events: list[HistoryEvent] = []
    for line in out.splitlines():
        ts, _, message = line.partition("\t")
        if not ts.isdigit():
            continue
        events.append(
            HistoryEvent(
                when=datetime.fromtimestamp(int(ts), tz=timezone.utc).astimezone(),
                project=name,
                message=message,
            )
        )
    return events
